{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 6}, "tests": {"0": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495D2C9590>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_isolation", "rerun": "0"}, "1": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495D3C35D0>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_durability", "rerun": "0"}, "2": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495EB06AD0>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_consistency", "rerun": "0"}, "3": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495EA3AD50>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_atomicity_commit", "rerun": "0"}, "4": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495EA4D210>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_atomicity_rollback", "rerun": "0"}, "5": {"status": "ERROR", "message": "self = <sqlalchemy.engine.base.Connection object at 0x000002495ED6D510>\nengine = Engine(postgresql://test_user:***@localhost:5432/legal_study_test), connection = None\n_has_events = None, _allow_revalidate = True, _allow_autobegin = True\n\n    def __init__(\n        self,\n        engine: Engine,\n        connection: Optional[PoolProxiedConnection] = None,\n        _has_events: Optional[bool] = None,\n        _allow_revalidate: bool = True,\n        _allow_autobegin: bool = True,\n    ):\n        \"\"\"Construct a new Connection.\"\"\"\n        self.engine = engine\n        self.dialect = dialect = engine.dialect\n    \n        if connection is None:\n            try:\n>               self._dbapi_connection = engine.raw_connection()\n\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       psycopg2.OperationalError: connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def db_manager() -> Generator[DatabaseManager, None, None]:\n        \"\"\"Create a database manager for testing.\"\"\"\n        manager = DatabaseManager()\n>       manager.create_tables()\n\n.tests\\test_acid.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi\\database.py:81: in create_tables\n    Base.metadata.create_all(engine)\n.venv\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py:5925: in create_all\n    bind._run_ddl_visitor(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3248: in _run_ddl_visitor\n    with self.begin() as conn:\n..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py:137: in __enter__\n    return next(self.gen)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3238: in begin\n    with self.connect() as conn:\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3274: in connect\n    return self._connection_cls(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:148: in __init__\n    Connection._handle_dbapi_exception_noconnection(\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:2439: in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:146: in __init__\n    self._dbapi_connection = engine.raw_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py:3298: in raw_connection\n    return self.pool.connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:449: in connect\n    return _ConnectionFairy._checkout(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:713: in checkout\n    rec = pool._do_get()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:179: in _do_get\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py:177: in _do_get\n    return self._create_connection()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:390: in _create_connection\n    return _ConnectionRecord(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:675: in __init__\n    self.__connect()\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:901: in __connect\n    with util.safe_reraise():\n.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:146: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py:897: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py:646: in connect\n    return dialect.connect(*cargs, **cparams)\n.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py:625: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndsn = 'host=localhost dbname=legal_study_test user=test_user password=test_password port=5432'\nconnection_factory = None, cursor_factory = None\nkwargs = {'dbname': 'legal_study_test', 'host': 'localhost', 'password': 'test_password', 'port': 5432, ...}\nkwasync = {}\n\n    def connect(dsn=None, connection_factory=None, cursor_factory=None, **kwargs):\n        \"\"\"\n        Create a new database connection.\n    \n        The connection parameters can be specified as a string:\n    \n            conn = psycopg2.connect(\"dbname=test user=postgres password=secret\")\n    \n        or using a set of keyword arguments:\n    \n            conn = psycopg2.connect(database=\"test\", user=\"postgres\", password=\"secret\")\n    \n        Or as a mix of both. The basic connection parameters are:\n    \n        - *dbname*: the database name\n        - *database*: the database name (only as keyword argument)\n        - *user*: user name used to authenticate\n        - *password*: password used to authenticate\n        - *host*: database host address (defaults to UNIX socket if not provided)\n        - *port*: connection port number (defaults to 5432 if not provided)\n    \n        Using the *connection_factory* parameter a different class or connections\n        factory can be specified. It should be a callable object taking a dsn\n        argument.\n    \n        Using the *cursor_factory* parameter, a new default cursor factory will be\n        used by cursor().\n    \n        Using *async*=True an asynchronous connection will be created. *async_* is\n        a valid alias (for Python versions where ``async`` is a keyword).\n    \n        Any other keyword parameter will be passed to the underlying client\n        library: the list of supported parameters depends on the library version.\n    \n        \"\"\"\n        kwasync = {}\n        if 'async' in kwargs:\n            kwasync['async'] = kwargs.pop('async')\n        if 'async_' in kwargs:\n            kwasync['async_'] = kwargs.pop('async_')\n    \n        dsn = _ext.make_dsn(dsn, **kwargs)\n>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\nE       sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)\nE       \tIs the server running on that host and accepting TCP/IP connections?\nE       \nE       (Background on this error at: https://sqlalche.me/e/20/e3q8)\n\n.venv\\Lib\\site-packages\\psycopg2\\__init__.py:122: OperationalError\n", "test_name": "test_concurrent_updates", "rerun": "0"}}, "suite_name": ".tests/test_acid.py"}}}, "date": "April 23, 2025", "start_time": 1745419988.4032228, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "6", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}