{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       Failed: DID NOT RAISE <class 'sqlalchemy.exc.IntegrityError'>\n", "test_name": "test_consistency", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_atomicity_commit", "rerun": "0"}, "2": {"status": "FAIL", "message": "       sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x1cb64c7ec50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)\n", "test_name": "test_concurrent_updates", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_atomicity_rollback", "rerun": "0"}, "4": {"status": "FAIL", "message": "       sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x1cb64cbfa10> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)\n", "test_name": "test_isolation", "rerun": "0"}, "5": {"status": "FAIL", "message": "       sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x1cb64cd8950> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)\n", "test_name": "test_durability", "rerun": "0"}}, "suite_name": ".tests/test_acid.py"}}}, "date": "April 23, 2025", "start_time": 1745420050.5001242, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}